services:
  db:
    image: postgres:15
    container_name: funny_db
    restart: always
    environment:
      POSTGRES_DB: funnydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: funny_web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=utils
      - DB_NAME=funnydb
      - DB_USER=postgres
      - DB_PASS=root

volumes:
  pgdata:
