services:
  db:
    image: postgres:15
    container_name: prism_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ks_bd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql_backup_with_data.sql:/docker-entrypoint-initdb.d/sql_backup_with_data.sql

  backend:
    build: ./db_backend
    container_name: prism_backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: prism
      DB_USER: postgres
      DB_PASS: postgres

  frontend:
    build: ./db_front
    container_name: prism_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
